version: 2.1

orbs:
  android: circleci/android@3.1.0

jobs:
  build:
    docker:
      - image: cimg/android:2025.04
    executor: android/android
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
            - v1-dependencies-
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
            - ~/.android/build-cache
            - ~/.android/cache
          key: v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Run Build
          command: ./gradlew build --build-cache
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - android/run-tests:
          test-command: ./gradlew lint test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: artifact-file
